
requests = [
    ('DELETE', '/orders/1', 200),
    ('GET', '/products/1', 200),
    ('POST', '/products', 403),
    ('DELETE', '/checkout', 400),
    ('DELETE', '/login', 200),
    ('PUT', '/products/1', 200),
    ('GET', '/login', 500),
    ('POST', '/products/1', 404),
    ('DELETE', '/logout', 403),
    ('POST', '/dashboard', 200),
    ('POST', '/api/users', 204),
    ('POST', '/checkout', 200),
    ('GET', '/logout', 200),
    ('PUT', '/cart', 204),
    ('PUT', '/api/users', 403),
    ('POST', '/logout', 201),
    ('PUT', '/settings', 403),
    ('GET', '/search', 403),
    ('GET', '/settings', 403),
    ('POST', '/products/1', 401),
    ('DELETE', '/products/1', 200),
    ('POST', '/orders', 200),
    ('DELETE', '/orders/1', 401),
    ('DELETE', '/api/users', 500),
    ('DELETE', '/settings', 401),
    ('POST', '/search', 404),
    ('PUT', '/products/2', 201),
    ('PUT', '/api/users', 200),
    ('GET', '/orders/1', 201),
    ('GET', '/orders/1', 200),
    ('GET', '/products/2', 200),
    ('GET', '/api/data', 200),
    ('POST', '/orders', 404),
    ('PUT', '/settings', 200),
    ('DELETE', '/cart', 404),
    ('POST', '/checkout', 201),
    ('PUT', '/orders', 200),
    ('GET', '/profile', 403),
    ('PUT', '/dashboard', 400),
    ('DELETE', '/products/1', 200),
    ('GET', '/cart', 200),
    ('GET', '/orders/1', 200),
    ('POST', '/products/2', 204),
    ('PUT', '/products/2', 200),
    ('PUT', '/checkout', 403),
    ('DELETE', '/profile', 200),
    ('POST', '/products', 400),
    ('POST', '/orders', 200),
    ('POST', '/login', 403),
    ('PUT', '/profile', 201),
    ('GET', '/checkout', 500),
    ('GET', '/checkout', 200),
    ('GET', '/profile', 400),
    ('GET', '/dashboard', 201),
    ('PUT', '/orders', 200),
    ('PUT', '/checkout', 201),
    ('DELETE', '/search', 403),
    ('DELETE', '/search', 400),
    ('GET', '/api/users', 500),
    ('PUT', '/products', 200),
    ('POST', '/cart', 200),
    ('PUT', '/login', 400),
    ('POST', '/logout', 404),
    ('PUT', '/products/2', 401),
    ('DELETE', '/orders', 200),
    ('POST', '/dashboard', 200),
    ('DELETE', '/search', 201),
    ('GET', '/api/users', 201),
    ('PUT', '/orders/1', 401),
    ('GET', '/settings', 204),
    ('POST', '/checkout', 401),
    ('POST', '/orders', 500),
    ('PUT', '/orders', 204),
    ('PUT', '/login', 200),
    ('PUT', '/products/1', 500),
    ('PUT', '/settings', 200),
    ('PUT', '/products', 200),
    ('POST', '/home', 500),
    ('DELETE', '/orders', 500),
    ('GET', '/logout', 200),
    ('PUT', '/products', 201),
    ('GET', '/dashboard', 200),
    ('POST', '/dashboard', 201),
    ('POST', '/orders/1', 400),
    ('PUT', '/products', 400),
    ('PUT', '/orders', 500),
    ('POST', '/settings', 401),
    ('POST', '/search', 200),
    ('POST', '/products/2', 204),
    ('DELETE', '/checkout', 204),
    ('GET', '/settings', 201),
    ('POST', '/checkout', 200),
    ('GET', '/orders/1', 403),
    ('PUT', '/checkout', 404),
    ('PUT', '/dashboard', 500),
    ('GET', '/settings', 403),
    ('GET', '/orders', 400),
    ('POST', '/dashboard', 401),
    ('DELETE', '/search', 200),
    ('GET', '/search', 204)
]

# ('GET', '/search', 204)
# ['GET', '/search', 204]

# Завдання
# 1. Вивести всі успішні запити (status_code = 200)
for method, url, status_code in requests:
    if status_code == 200:
        print(method, url, status_code)

# _ - замість назви змінної, якщо нам вона не потрібна
for _, _, status_code in requests:
    if status_code == 200:
        print(status_code)

# 2. Знайдіть унікальні URL, на яких виникали помилки (status_code != 200).

