# Generated by Django 6.0.4 on 2026-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_is_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="number_of_classes",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
