# Generated by Django 6.0.4 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_author_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(
                choices=[
                    ('teacher', 'teacher'),
                    ('student', 'student'),
                ],
                default='student',
                max_length=20,
            ),
        ),
    ]
